# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-26 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='deposit',
            field=models.IntegerField(default=0, verbose_name='房屋押金'),
        ),
    ]
