# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-03 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20190626_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='capacity',
            field=models.IntegerField(default=1, verbose_name='房屋容纳'),
        ),
        migrations.AlterField(
            model_name='house',
            name='max_days',
            field=models.IntegerField(default=0, verbose_name='最大入住天数'),
        ),
        migrations.AlterField(
            model_name='house',
            name='min_days',
            field=models.IntegerField(default=1, verbose_name='最少入住天数'),
        ),
        migrations.AlterField(
            model_name='house',
            name='room_count',
            field=models.IntegerField(default=1, verbose_name='房间数目'),
        ),
    ]
