# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-03 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(verbose_name='订单的总金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house_price',
            field=models.IntegerField(verbose_name='房屋的单价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAIT_ACCEPT', '待接单'), ('WAIT_PAYMENT', '待支付'), ('PAID', '已支付'), ('WAIT_COMMENT', '待评价'), ('COMPLETE', '已完成'), ('CANCELED', '已取消'), ('REJECTED', '已拒单')], default='WAIT_ACCEPT', max_length=50, verbose_name='订单状态'),
        ),
    ]
