# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-03 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190703_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='days',
            field=models.IntegerField(verbose_name='预订的总天数'),
        ),
    ]
